DROP DATABASE IF EXISTS EMPLEADOS;
CREATE DATABASE EMPLEADOS;
ALTER DATABASE EMPLEADOS DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

use EMPLEADOS;

DROP TABLE IF EXISTS TEMPLE;
DROP TABLE IF EXISTS TDEPTO;
DROP TABLE IF EXISTS TCENTR;

CREATE TABLE TCENTR
(NUMCE INTEGER NOT NULL,
 NOMCE VARCHAR(30) NOT NULL,
 SENAS VARCHAR(50) NOT NULL,
 PRIMARY KEY (NUMCE))
 ENGINE=InnoDB;


CREATE TABLE TDEPTO
(NUMDE INTEGER NOT NULL,
 NUMCE INTEGER,
 DIREC INTEGER NOT NULL,
 TIDIR CHAR(1) NOT NULL,
 PRESU DECIMAL(6,1) NOT NULL,
 DEPDE INTEGER,
 NOMDE VARCHAR(20) NOT NULL,
 PRIMARY KEY (NUMDE),
 FOREIGN KEY (NUMCE) REFERENCES TCENTR(NUMCE) ON DELETE RESTRICT )
 ENGINE=InnoDB;


CREATE TABLE TEMPLE
(NUMEM INTEGER       NOT NULL,
 NUMDE INTEGER       NOT NULL,
 EXTEL INTEGER       NOT NULL,
 FECNA DATE          NOT NULL,
 FECIN DATE          NOT NULL,
 SALAR DECIMAL(6,1)  NOT NULL,
 COMIS DECIMAL(6,1),
 NUMHI SMALLINT      NOT NULL,
 NOMEM VARCHAR(20)   NOT NULL,
 PRIMARY KEY (NUMEM),
 FOREIGN KEY (NUMDE) REFERENCES TDEPTO (NUMDE) ON DELETE RESTRICT )
 ENGINE=InnoDB;



LOAD DATA INFILE '/var/lib/mysql-files/tcentr.txt' INTO TABLE TCENTR;
LOAD DATA INFILE '/var/lib/mysql-files/tdepto.txt' INTO TABLE TDEPTO;
LOAD DATA INFILE '/var/lib/mysql-files/temple.txt' INTO TABLE TEMPLE;


