{{- if .Values.persistence.mysqlData.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: {{ include "icai-introbbdd.namespace" . }}
  labels:
    {{- include "icai-introbbdd.labels" . | nindent 4 }}
    volume: mysql-data
spec:
  accessModes:
    - {{ .Values.persistence.mysqlData.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.mysqlData.size }}
  storageClassName: {{ .Values.persistence.mysqlData.storageClass }}
---
{{- end }}
{{- if .Values.persistence.workspace.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc
  namespace: {{ include "icai-introbbdd.namespace" . }}
  labels:
    {{- include "icai-introbbdd.labels" . | nindent 4 }}
    volume: workspace
spec:
  accessModes:
    - {{ .Values.persistence.workspace.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.workspace.size }}
  storageClassName: {{ .Values.persistence.workspace.storageClass }}
{{- end }}