apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: introbbdd
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: cochimbo/introbbddicade
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "comillas"
        - name: MYSQL_CHARSET
          value: "utf8mb4"
        - name: MYSQL_COLLATION
          value: "utf8mb4_general_ci"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: workspace
          mountPath: /workspace
        - name: mysql-init-scripts
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pvc
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace-pvc
      - name: mysql-init-scripts
        configMap:
          name: mysql-init-scripts