apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  namespace: introbbdd
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /opt/icai-mysql-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv
  namespace: introbbdd
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /opt/icai-workspace